### ISSUE TITLE
PostgreSQL 10.4 on RDS/Aurora is not supported as a DMS target

### ISSUE THREAD

**Issue by vgeshel** [awsdocs/aws-dms-user-guide#10]
Due to this problem: https://forums.aws.amazon.com/thread.jspa?messageID=860564&tstart=0

Also confirmed by AWS support.

The documentation doesn't reflect this.

**Comment by chrmcguire** [comment]
The using PostgreSQL as a target section of the DMS User Guide has been updated since this issue was first reported.  

Closing the issue.
