### ISSUE TITLE
Mysql bug in full load with DMS

### ISSUE THREAD

**Issue by aroca** [awsdocs/aws-dms-user-guide#11]
This bug causes that not all data being loaded to the target database.

The solution is to add an ECA.

If you ok guys, I will add this to the Mysql troubleshooting section.

Cheers!

**Comment by aroca** [comment]
Ping fellows. Just to know if its ok to create a PR for this.

**Comment by hpaknia** [comment]
I am experiencing this issue. Only 48,000 rows of 76,000 rows in the target are migrated to the destination. I am not sure if it is related to the bug you are reporting. 
Any updates on this? Can you explain the root cause? Any workarounds?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
