### ISSUE TITLE
dms error out when the source index name contains empty space

### ISSUE THREAD

**Issue by syu2222** [awsdocs/aws-dms-user-guide#12]
Hi, I am migrating a Microsoft SqlServer database to RDS MySql. There is an error in the task because the source index name has empty space:
2018-11-21T04:47:05 [TARGET_LOAD ]E: RetCode: SQL_ERROR SqlState: HY000 NativeError: 1280 Message: [MySQL][ODBC 5.3(w) Driver][mysqld-5.7.23-log]Incorrect index name 'fuelsolutionheader_pk_fuelsolutionheader ' [1022502] (ar_odbc_stmt.c:4615)

The definition of the index in the source database is:
CREATE UNIQUE INDEX [pk_fuelsolutionheader ] ON dbo.fuelsolutionheader (lgh_number,request_id)

Notice that there is empty space at the end of the [pk_fuelsolutionheader ].
Since our goal is to migrate data over and don't worry about the extra space in the index name, can AWS DMS handle such typo cases (for example, trim the empty space) and finish the migration successfully?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
