### ISSUE TITLE
Docs on Kinesis target are incomplete

### ISSUE THREAD

**Issue by dskrvk** [awsdocs/aws-dms-user-guide#16]
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.Kinesis.html

In the section on **Object Mapping** the guide explains what `map-record-to-record` means, but all the examples only show rules for `map-record-to-document`. Conversely, there's no verbal explanation of what the latter type of mapping does.

Additionally, it's not clear whether the generated events are the same for each type of `Operation` or if e.g. the `update` one only contains the updated fields.

Also, why is a `read` event generated if it doesn't seem to correspond to a **change** in the source database?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
