### ISSUE TITLE
Issues with AWS DMS SQL Server Endpoint documentation

### ISSUE THREAD

**Issue by AaronTC05** [awsdocs/aws-dms-user-guide#21]
**Pick a terminology for AWS DMS’s method for capturing data changes and stick with it consistently throughout.  I like “Ongoing Replication” with no reference to CDC/change data capture because as a SQL DBA, CDC and change data capture are features of the SQL Server product so when you refer to Aws DMS’s technology as CDC/change data capture it is extremely confusing what is being referred to.  Stick to AWS DMS technology as “Ongoing Replication” and MS-Replication and MS-CDC for Microsoft technologies.**

> To use CDC with SQL Server, you must create a publication for each table that is participating in ongoing replication.

- **Instead of CDC say “Ongoing Replication”** 

> 9. Choose Security Settings and choose Run under the SQL Server Agent service account. Make sure to choose By impersonating the process account for publisher connection. Choose OK.

**I assume this is for the Snapshot Agent “Security Settings” since the wizard won’t let you move past the Agent Security screen without this set.  But there’s two “Security Settings” buttons so it’s not 100% clear** 

> Provide a name of the publication in the format AR_PUBLICATION_000<DBID>.

- **If the DBID is a single digit (ex: 6) does the name have to be AR_PUBLICIATION_00006 (add another 0)?  That is what is created when the publication is created by the DMS tool.**

- **If this is required then this should be noted, otherwise I would create the publication as AR_PUBLICIATION_0006 when following the instructions explicitly and without knowing how the automated process works.**

> 	Enable the Distribution option on all SQL Server instances in your Availability Replicas.

- **This sounds like you’re talking about a feature of Always ON Availability Groups, when in reality I think you’re referring to setting up the distribution database for the MS-Replication install on the replicas.**

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
