### ISSUE TITLE
Failing to Register DMS Agent in SCT

### ISSUE THREAD

**Issue by praku007** [awsdocs/aws-dms-user-guide#23]
DMS Agent is not starting the service on the Linux Box and status always shows as not running.
Is there a log file that can be viewed to see the errors.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
