### ISSUE TITLE
Missing ValidationSettings documentation

### ISSUE THREAD

**Issue by omnibs** [awsdocs/aws-dms-user-guide#28]
There seem to be more settings on the JSON for Validation than the documentation shows. I see:

```json
    "ValidationSettings": {
        "EnableValidation": true,
        "ValidationMode": "ROW_LEVEL",
        "ThreadCount": 5,
        "PartitionSize": 10000,
        "FailureMaxCount": 10000,
        "RecordFailureDelayInMinutes": 5,
        "RecordSuspendDelayInMinutes": 30,
        "MaxKeyColumnSize": 8096,
        "TableFailureMaxCount": 1000,
        "ValidationOnly": false,
        "HandleCollationDiff": false,
        "RecordFailureDelayLimitInMinutes": 0
    },
```

I haven't found docs on other settings than `EnableValidation` and `ThreadCount`. Googling for `"Data Migration Service" "ValidationSettings" "MaxKeyColumnSize"` for instance turns out no results.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
