### ISSUE TITLE
Please clarify in the documentation if DMS creates the schema when the parameter `ddlArtifactsSchema` is set

### ISSUE THREAD

**Issue by cabcookie** [awsdocs/aws-dms-user-guide#30]
In `doc_source/CHAP_Troubleshooting.md` there is mentioned we can create the DDL artifacts in a separate schema by setting the schema name in the parameter `ddlArtifactsSchema`. Please clarify if then DMS creates this schema itself or does DMS expects this schema to exist already?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
