### ISSUE TITLE
CHAP_Target.S3.DatePartitioning document does not exist

### ISSUE THREAD

**Issue by marco48134** [awsdocs/aws-dms-user-guide#32]
CHAP_Target.S3.DatePartitioning document does not exist even though the feature was announced via https://aws.amazon.com/about-aws/whats-new/2020/10/aws-database-migration-service-supports-transaction-commit-date-partitioning-cdc-mode-using-s3-target/. See “Use date partitioning when using S3 as a target” link leads to the DMS welcome page.

**Comment by AWSdnrose** [comment]
I have created an internal SIM to fix this issue and will therefore close it here.
