### ISSUE TITLE
Where is use3rdPartyBackupDevice documented?

### ISSUE THREAD

**Issue by stevebanik** [awsdocs/aws-dms-user-guide#33]

**Comment by AWSdnrose** [comment]
This option is documented in a table of the "Extra connection attributes when using SQL Server as a source
for AWS DMS" section in the Database Migration Service User Guide, here: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html#CHAP_Source.SQLServer.ConnectionAttrib
