### ISSUE TITLE
Please document all endpoint extra connection attributes

### ISSUE THREAD

**Issue by yoni-yad2** [awsdocs/aws-dms-user-guide#42]
such as:
```
ConnectTimeout 
ExecuteTimeout
CdcTimeout 
UnloadTimeout
ResumeFetchForXRows
...
...
...
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
